#!/usr/bin/env python3
"""Rebuild automatic examples and compare saved manual regression plans."""
import json
from pathlib import Path
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import build
from aipe_sketch.manual_topologies import CATALOGUE
from aipe_sketch.manual_synthetic import SYNTHETIC
from aipe_sketch import validate


def compare():
    baselines = dict(CATALOGUE, **SYNTHETIC)
    results = []
    with tempfile.TemporaryDirectory() as manual_dir:
        for name in build.CATALOGUE:
            auto, card, log, path = build.build(name)
            result = dict(circuit=name, automatic=card.overall,
                          valid=not validate.check(auto.netlist, auto.placed, auto.paths),
                          acceptable=card.acceptable, selected=auto.selected_candidate,
                          candidates=len(auto.candidate_report), manual=None)
            if name in baselines:
                manual, baseline, _, _ = build.build(name, manual_dir, manual=True)
                if auto.netlist.signature() != manual.netlist.signature():
                    raise AssertionError(f'{name}: manual and automatic IR differ')
                result['manual'] = baseline.overall
            results.append(result)
    target = ROOT / 'docs' / 'auto-planning-results.md'
    lines = ['# Automatic / manual regression comparison', '',
             'Generated by `python3 tools/compare_plans.py`. All outputs use the',
             'canonical master SVG. Validity means reconstructed drawn connectivity',
             'matches Circuit IR; acceptable also checks collisions and hard drawing rules.', '',
             '| Circuit | Automatic | Manual baseline | Electrically valid | Acceptable | Selected candidate |',
             '| --- | ---: | ---: | --- | --- | ---: |']
    for r in results:
        lines.append(f'| {r["circuit"]} | {r["automatic"]} | '
                     f'{r["manual"] if r["manual"] is not None else "—"} | '
                     f'{r["valid"]} | {r["acceptable"]} | {r["selected"]} |')
    lines += ['', 'Scores measure general properties and contain no converter-name branches.',
              'Each automatic build evaluates 12 deterministic geometry candidates.',
              'Soft aesthetic warnings remain in the scorecards; validity is a hard gate.',
              'SVGs are in `out/`. The tests additionally rename/reorder graphs, check',
              'source-free interfaces and verify that deliberate shorts are rejected.', '']
    target.write_text('\n'.join(lines))
    (ROOT / 'docs' / 'auto-planning-results.json').write_text(json.dumps(results, indent=2) + '\n')
    return results


if __name__ == '__main__':
    for result in compare():
        print(f'{result["circuit"]}: auto={result["automatic"]} '
              f'manual={result["manual"]} valid={result["valid"]}')
